version: "3.1"

services:
    laravel:
        image: laravel-docker
        build:
            context: .
            dockerfile: ./src/Dockerfile
            target: laravel
        ports:
            - "${APP_PORT:-80}:80"
        env_file:
            - .env

    mysql:
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql:/var/lib/mysql'

volumes:
    mysql:
